name: sqlite_search_engine
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  sqflite_repo:
    git:
      url: https://github.com/johnmelodyme27/sqflite.git
      ref: v1.3.1

  sqflite: ^1.3.0

  path_provider: ^1.6.21
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true