name: sqlite_search_engine
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  sqflite_repo:
    git:
      url: https://github.com/johnmelodyme27/sqflite.git
      ref: v1.3.1

  fluttertoast:
    git:
      url: https://github.com/ponnamkarthik/FlutterToast.git


  simple_permissions:
    git:
      url: https://github.com/johnmelodyme/simple_permissions.git
      ref: 0.1.0

  sqflite: any

  url_launcher: ^5.4.2

  path_provider: ^1.6.21

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true